:toc:
= Démo sur un projet Python

Application progressive des hooks natifs sur expylliarmus

== Tri des imports avec isort 1/2

Ajout du hook dans `.pre-commit-config.yaml` :

[source,yaml]
----
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        # required for python projects configured with a pyproject.toml file
        additional_dependencies: [toml]
----

== Tri des imports avec isort 2/2

Configuration de isort dans `pyproject.toml` :

[source, toml]
----
[tool.isort]
# the line length must be specified for isort too to handle multi-line in a way compatible with yapf
line_length = 120
# Hanging Grid Grouped (mode 5)
# from third_party import (
#     lib1, lib2, lib3, lib4,
#     lib5, etc.
# )
multi_line_output = 5
balanced_wrapping = false
# moves the imports of the local tests module in a separate section
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER", "TESTS"]
known_tests = ["tests"]
----

== Formatage de code avec yapf 1/2

Ajout du hook dans `.pre-commit-config.yaml` :

[source,yaml]
----
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        name: Yapf
        # required for python projects configured with a pyproject.toml file
        additional_dependencies: [toml]
----

== Formatage de code avec yapf 2/2

Configuration de yapf (dans `pyproject.toml`) où les parenthèses sont refermées à la ligne :

[source, toml]
----
[tool.yapf]
based_on_style = "facebook"
# see the https://github.com/google/yapf#knobs section
COALESCE_BRACKETS = false
COLUMN_LIMIT = 120
DEDENT_CLOSING_BRACKETS = true
INDENT_DICTIONARY_VALUE = false
EACH_DICT_ENTRY_ON_SEPARATE_LINE = true
FORCE_MULTILINE_DICT = true
JOIN_MULTIPLE_LINES = false
SPACES_AROUND_DEFAULT_OR_NAMED_ASSIGN = false
SPLIT_BEFORE_CLOSING_BRACKET = true
SPLIT_BEFORE_DICT_SET_GENERATOR = true
SPLIT_COMPLEX_COMPREHENSION = true
SPLIT_BEFORE_EXPRESSION_AFTER_OPENING_PAREN = true
SPLIT_BEFORE_FIRST_ARGUMENT = true
----

Alternatives : black (volontairement sans configuration)


== Analyse de pratiques avec ruff 1/2

[source,yaml]
----
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.95
    hooks:
      - id: ruff
----

== Analyse de pratiques avec ruff 2/2

Configuration de isort dans `pyproject.toml` :

[source, toml]
----
[tool.ruff]
line-length = 120
select = ["E", "F"]
ignore = ["E501"]
per-file-ignores = {
    "__init__.py" = ["F401"],
    "path/to/file.py" = ["F401"]
}
----

== Méthodologie

[%step]
Discuter les règles de formatage en équipe (communautés de pratiques Python)
* nuancer les règles indispensable et celles de goût
* adapter au besoin métier (tests unitaires de TLN -> guillemets doubles)
* tester les règles sur la base de code puis discuter les différences obtenues en équipe
* accepter les compromis faits par yapf : il y aura des cas où le résultat ne sera pas foufou, le but est de tendre vers une homogénéité de la base de code